### PR TITLE
fix: id:48167 Tab component HTML structure change

### PR DESCRIPTION
**Pull request by Farhan-emgage**
Tab component HTML structure change

### CODE REVIEW

**Comment by emgageadmin** [comment]
https://atera.tpondemand.com/entity/48167

**Review by weegrom — CHANGES_REQUESTED** [review]
@Farhan-emgage two things:
1. This needs to use functions for specifying colors (ex: theme-color(m-grey, 900); )
1. This should likely this have a stylesheet added to Delicious theme

**Comment by Farhan-emgage** [comment]
@weegrom i had given variable color instead of static color code. exact color is not found so it might some variation

**Review by weegrom — CHANGES_REQUESTED** [review]
@Farhan-emgage the colors you provided will not work in this file, as this is the base component stylesheet and not the style overrides via the Delicious theme. You're limited to the colors avaible in the base styling, as defined in https://github.com/emgage/engage-ui/blob/master/src/styles/foundation/colors.scss . Please fix this, and also add overrides for the Tab component to Delicious. You can view the Delicious styling for the tab in https://www.figma.com/file/Ff3voHzTudQyla2AAfwmDt/emgage-ui-Components?node-id=915%3A7720

**Comment by Farhan-emgage** [comment]
I added color property in color.scss and apply the variable in Tab.scss

**Review by weegrom — CHANGES_REQUESTED** [review]
@Farhan-emgage  you now have duplicate color vars, as (sky, base) and (grey, lighter) are exactly the same. Please remove the colors you added and instead use:
sky, base (#dfe3e8)
ink, lighter (#637381)
ink, base (#212b36)

You should be able to figure out which color is to be assigned where.

**Comment by Farhan-emgage** [comment]
changed color variable

**Review by weegrom — APPROVED** [review]

**Pull request merged**
