### PR TITLE
fix: id:43944 added declaration types

### PR DESCRIPTION
**Pull request by HirenTariwala**

### CODE REVIEW

**Comment by dheeraja00** [comment]
@harsimranb Can you please take a look at this PR, I think you might be the right person to review this one, I have taken a look & things are looking ok to me.

@weegrom

**Comment by emgage** [comment]
@harsimranb can you please review this so we can get it merged. Thanks

**Comment by harsimranb** [comment]
@HirenTariwala It looks good to me.  Did you create a simple React TS project, add this engage-ui as reference, and verify the TS hints show up for our components?  That would be good verification that it is all setup correctly.

@dheeraja00 @weegrom

**Comment by HirenTariwala** [comment]
Sure @harsimranb Let me check. I've earlier checked with Emgage-FE It was working fine.

**Comment by HirenTariwala** [comment]
Screenshot from 2020-03-18 11-53-53
Working fine @harsimranb

**Comment by harsimranb** [comment]
@HirenTariwala @dheeraja00 approved.  Merge at your discretion.

**Pull request merged**
