### PR TITLE
Bugfix/47831 tab component accessibility

### PR DESCRIPTION
**Pull request by Farhan-emgage**
tab component accessibility

### CODE REVIEW

**Comment by emgageadmin** [comment]
https://atera.tpondemand.com/entity/47831

**Review by weegrom — CHANGES_REQUESTED** [review]
@Farhan-emgage please see my comments

**Comment by weegrom** [comment]
@Farhan-emgage what's holding up the requested changes on this PR?

**Comment by emgageadmin** [comment]
https://atera.tpondemand.com/entity/47831

**Pull request closed without merging**
