### PR TITLE
fix: id:54607 add text in next previous button in pagination

### PR DESCRIPTION
**Pull request by Farhan-emgage**
add text in next previous button in pagination

### CODE REVIEW

**Comment by emgageadmin** [comment]
https://atera.tpondemand.com/entity/54607

**Review by weegrom — CHANGES_REQUESTED** [review]
Hey @Farhan-emgage - Couple changes:

1. Simplify the text to "Previous" and "Next"
2. On the ul element wrapping the pagination include an aria label or visually hidden text "Pagination". This way a user using a screen reading will know what the list of items is/does/

Thanks

**Comment by Farhan-emgage** [comment]
@weegrom  the changes is done

**Review by weegrom — COMMENTED** [review]
@Farhan-emgage here also, why are we not using the button components accessibilityLabel prop?

**Comment by Farhan-emgage** [comment]
@weegrom actually accesibilityLabel props is use for screen read. but here we are placing visually hidden component because icon is not considered as text. so screen consider it as a blank button.

image

**Comment by weegrom** [comment]
@Farhan-emgage shouldn't adding the "aria-label" (accessibilityLabel prop) be sufficient? If not, we need to make an adjustment to the button component to make it accessible. We should not require the dev to add a visually hidden component if they've already added the accessibilityLabel prop.

**Pull request closed without merging**
