### PR TITLE
Bugfix/47956 table component accessibility

### PR DESCRIPTION
**Pull request by Farhan-emgage**
table component accessibility

### CODE REVIEW

**Comment by emgageadmin** [comment]
https://atera.tpondemand.com/entity/47956

**Review by weegrom — COMMENTED** [review]
@Farhan-emgage let's discuss the tabIndex changes. I want to understand why this prop is being added. We should not require the dev to set tabIndex, but instead be in programmatically (if it's even needed)

**Comment by weegrom** [comment]
@Farhan-emgage what's the status on this?

**Comment by emgageadmin** [comment]
https://atera.tpondemand.com/entity/47956

**Pull request closed without merging**
