### PR TITLE
44870 update react-router and redux

### PR DESCRIPTION
**Pull request by volodymyr-code**

### CODE REVIEW

**Comment by ankitsaraogi** [comment]
@volodymyr-code : Can you please confirm if all the code that we removing isnt getting used anywhere.
Also please check pipeline

**Comment by volodymyr-code** [comment]
> @volodymyr-code : Can you please confirm if all the code that we removing isnt getting used anywhere.
> Also please check pipeline

in my opinion, all works fine, confirm
pipeline depends on merging builder and ui PRs

**Comment by volodymyr-code** [comment]
I can run build locally and leave output here

**Pull request merged**
